### ISSUE TITLE
Cutoff color palette 

### ISSUE THREAD

**Issue by fominv** [Fuchs/hoppla-sa#14]
Firstly, i want to thank you for making this beautiful piece of software!

The only problem i have with it is that the color palette in the *lights* section is cutoff. I attached a gif  to demonstrate the problem. Additionally, the upper part of the first entry seems also to be cutoff which i assume might be related.

![issue](https://user-images.githubusercontent.com/35870867/69756752-85a37680-115b-11ea-997b-b985c5603182.gif)

**Comment by Fuchs** [comment]
Hi, thanks for the report

thats some very odd spacing indeed. 

May I ask you 

- what version of plasma you are using
- what version of Qt
- what font size
- any kind of scaling  (e.g. high dpi displays)

**Comment by Fuchs** [comment]
Also for a quick fix you can edit the height of 

lightDetailsItem   in LightItem.qml 
groupDetailsItem in GroupItem.qml 

for the height of the expanded light / group, and the size of the color item (the circle) is in HueColourItem.qml. 

You can edit it with any text editor an then just reload plasma and you should see changes imediately.

Kind regards

**Comment by Fuchs** [comment]
This should be halfway-fixed by the commit I just did, please try it out. 

I have no good explanation for the circle yet, but your icons seem to be rather huge. Is that a high resolution panel / scaling? If so: I unfortunately have none of these to test, so any fixes welcome. 

If it does fix both problems (or even one) please let me know here, then I'll bundle up a new release when I have the time.

**Comment by Fuchs** [comment]
Should be fixed with the most recent commit, otherwise I'm afraid I am not able to reproduce.

**Comment by fominv** [comment]
> Hi, thanks for the report
> 
> thats some very odd spacing indeed.
> 
> May I ask you
> 
>     * what version of plasma you are using
> 
>     * what version of Qt
> 
>     * what font size
> 
>     * any kind of scaling  (e.g. high dpi displays)

Thank you for the responses. Somehow i missed the reply notifications. Sorry for that! I updated the widget, but sadly the problem persists.

My configuration/versions are as follows:

- Operating System: Manjaro KDE
- Qt: 5.13.2
- Plasma: 5.17.3
- Display Scaling: 1.5, due to resolution of 3440x1440
- Font Sizes: Attached in screenshot.

![Screenshot_20191208_133346](https://user-images.githubusercontent.com/35870867/70389429-73c59d00-19bf-11ea-87f0-d7639afa86da.png)

I will try out the fixes you suggested and report back.

**Comment by Fuchs** [comment]
I did some more fixes that also include scaling, but I have to simulate that, which makes it a bit harder to reproduce the issue. 

You can check out in the latest commits which sizing related lines I adapted, you should be able to modify these with a text editor and then reload plasma. If you find settings that work well for you, please let me know.

Depending on how you installed the plasmoid, the files might be in  /usr/share/plasma/plasmoids,   ~/.local/share/plasma/plasmoids or some other plasma path, but the parent folder should always be ch.fuchsnet.plasma.hoppla-sa  so you can look for that. Note that a plasmoids in your home would override the global one.

**Comment by fominv** [comment]
Can confirm that the two recent commits fixed all issues. Marvelous work! Thank you, i wish you all the best! 👏 😎

**Comment by Fuchs** [comment]
Yay! Glad to hear, thanks for testing and happy holiday season :)
